package phonebook;

import java.util.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.DefaultListModel;

public class phonebook extends javax.swing.JFrame {

    public phonebook() {
        initComponents();
        
        contacts = new ArrayList<>();
        recent =  new LinkedList<>();
        contacts.add(new Contact("Eliah Celino", "09570759737", "eli.celino@gmail.com"));
        contacts.add(new Contact("Maria Santos", "09171234567", "maria.santos@gmail.com"));
        contacts.add(new Contact("Juan Dela Cruz", "09281234567", "juan.delacruz@yahoo.com"));
        contacts.add(new Contact("Josefa Garcia", "09391234567", "josefa.garcia@hotmail.com"));
        contacts.add(new Contact("Andres Reyes", "09451234567", "andres.reyes@aol.com"));
        contacts.add(new Contact("Rizalina Aquino", "09561234567", "rizalina.aquino@outlook.com"));


        updateContactList();
    }
    
    private ArrayList<Contact> contacts;
    private Queue<String> recent;
    
    //method to show home panel
    private void showHomePanel() {
        home_panel.setVisible(true);
        add_panel.setVisible(false);
        edit_panel.setVisible(false);
        view_panel.setVisible(false);
    }

    
    //methods to update contacts
    private void updateContactList() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Contact c : contacts) {
            model.addElement(c.getName());
        }
        list.setModel(model);
    }
    
    private String name;
    private String number;
    private String email;
    
    //methods to add contacts
    private void addContact(){
        
        
        name = name_textfield.getText();
        number = number_textfield.getText();
        email = email_textfield.getText();
        
            if (!validateName(name)) {
                JOptionPane.showMessageDialog(this, "Name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!validateNumber(number)) {
                JOptionPane.showMessageDialog(this, "Number must be 11 digits.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!validateEmail(email)) {
                JOptionPane.showMessageDialog(this, "Enter correct Email format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        contacts.add(new Contact(name, number, email));
        updateContactList(); 
        
        JOptionPane.showMessageDialog(this, "Contact Added Successfully", "Notice", JOptionPane.INFORMATION_MESSAGE);
        
        showHomePanel();
        
        name_textfield.setText("");
        number_textfield.setText("");
        email_textfield.setText("");
    }
    
    //validations for text fields
        private boolean validateName(String name) {
            return !name.isEmpty();
        }

        private boolean validateNumber(String number) {
            return number.matches("\\d{11}");
        }

        private boolean validateEmail(String email) {
        //  regex pattern
        String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email != null && email.matches(emailPattern);
    }


    
    
    //methods to remove contacts
    private void removeSelectedContact() {
        int selectedIndex = list.getSelectedIndex();
        if (selectedIndex != -1) {
            contacts.remove(selectedIndex);
            updateContactList();
        } else {
            JOptionPane.showMessageDialog(this, "No contact selected to remove.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     //methods to update recenlt viewed
    private void updateRecent() {
        String recent = recent_name_lbl.getText();
        if (!recent.equals("No recently viewed yet.")) {
            boolean found = false;
            for (Contact c : contacts) {
                if (recent.equals(c.getName())) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                recent_name_lbl.setText("No recently viewed yet.");
            }
        }
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_panel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        recent_name_lbl = new javax.swing.JLabel();
        contacts_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        recently_lbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        view_btn = new javax.swing.JButton();
        ADD_BTN = new javax.swing.JButton();
        del_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        edit_panel = new javax.swing.JPanel();
        header_edit_lbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edit_name_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edit_num_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edit_email_field = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        add_panel = new javax.swing.JPanel();
        header_add_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        number_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        back_btn1 = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        view_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        name_lbl_view = new javax.swing.JLabel();
        okay_btn = new javax.swing.JButton();
        number_view = new javax.swing.JLabel();
        number_placeholder = new javax.swing.JLabel();
        email_view = new javax.swing.JLabel();
        email_placeholder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 640));
        setMinimumSize(new java.awt.Dimension(360, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 640));
        getContentPane().setLayout(new java.awt.CardLayout());

        home_panel.setBackground(new java.awt.Color(244, 239, 250));
        home_panel.setMaximumSize(new java.awt.Dimension(360, 640));
        home_panel.setMinimumSize(new java.awt.Dimension(360, 640));
        home_panel.setLayout(null);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Phonebook.png"))); // NOI18N
        home_panel.add(header);
        header.setBounds(0, 0, 360, 55);

        recent_name_lbl.setBackground(new java.awt.Color(51, 255, 0));
        recent_name_lbl.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        recent_name_lbl.setForeground(new java.awt.Color(47, 24, 75));
        recent_name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recent_name_lbl.setText("No recently viewed yet.");
        recent_name_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recent_name_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recent_name_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recent_name_lblMouseExited(evt);
            }
        });
        home_panel.add(recent_name_lbl);
        recent_name_lbl.setBounds(20, 90, 330, 40);

        contacts_lbl.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        contacts_lbl.setForeground(new java.awt.Color(155, 114, 207));
        contacts_lbl.setText("Contacts");
        home_panel.add(contacts_lbl);
        contacts_lbl.setBounds(20, 150, 114, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(155, 114, 207));
        jLabel2.setText("________________________________________________________________");
        home_panel.add(jLabel2);
        jLabel2.setBounds(20, 126, 310, 30);

        recently_lbl1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        recently_lbl1.setForeground(new java.awt.Color(155, 114, 207));
        recently_lbl1.setText("Recently Viewed");
        home_panel.add(recently_lbl1);
        recently_lbl1.setBounds(20, 67, 114, 26);

        jScrollPane1.setBackground(new java.awt.Color(200, 177, 228));

        list.setBackground(new java.awt.Color(200, 177, 228));
        list.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        list.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        list.setSelectionBackground(new java.awt.Color(155, 114, 207));
        list.setSelectionForeground(new java.awt.Color(47, 24, 75));
        jScrollPane1.setViewportView(list);

        home_panel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 310, 280);

        view_btn.setBackground(new java.awt.Color(200, 177, 228));
        view_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        view_btn.setForeground(new java.awt.Color(47, 24, 75));
        view_btn.setText("VIEW");
        view_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        home_panel.add(view_btn);
        view_btn.setBounds(180, 490, 140, 40);

        ADD_BTN.setBackground(new java.awt.Color(200, 177, 228));
        ADD_BTN.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        ADD_BTN.setForeground(new java.awt.Color(47, 24, 75));
        ADD_BTN.setText("ADD");
        ADD_BTN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ADD_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_BTNActionPerformed(evt);
            }
        });
        home_panel.add(ADD_BTN);
        ADD_BTN.setBounds(30, 490, 140, 40);

        del_btn.setBackground(new java.awt.Color(200, 177, 228));
        del_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        del_btn.setForeground(new java.awt.Color(204, 0, 0));
        del_btn.setText("DELETE");
        del_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });
        home_panel.add(del_btn);
        del_btn.setBounds(180, 540, 140, 40);

        update_btn.setBackground(new java.awt.Color(200, 177, 228));
        update_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(47, 24, 75));
        update_btn.setText("EDIT");
        update_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        home_panel.add(update_btn);
        update_btn.setBounds(30, 540, 140, 40);

        getContentPane().add(home_panel, "card2");

        edit_panel.setBackground(new java.awt.Color(244, 239, 250));
        edit_panel.setMaximumSize(new java.awt.Dimension(360, 640));
        edit_panel.setMinimumSize(new java.awt.Dimension(360, 640));

        header_edit_lbl1.setBackground(new java.awt.Color(200, 177, 228));
        header_edit_lbl1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        header_edit_lbl1.setForeground(new java.awt.Color(47, 24, 75));
        header_edit_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_edit_lbl1.setText("EDIT CONTACT");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel6.setText("Name");

        edit_name_field.setBackground(new java.awt.Color(200, 177, 228));
        edit_name_field.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        edit_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_name_fieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel7.setText("Mobile Number");

        edit_num_field.setBackground(new java.awt.Color(200, 177, 228));
        edit_num_field.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        edit_num_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_num_fieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel8.setText("Email ");

        edit_email_field.setBackground(new java.awt.Color(200, 177, 228));
        edit_email_field.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        edit_email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_email_fieldActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(200, 177, 228));
        back_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(47, 24, 75));
        back_btn.setText("Back");
        back_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        save_btn.setBackground(new java.awt.Color(200, 177, 228));
        save_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(47, 24, 75));
        save_btn.setText("Save");
        save_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_panelLayout = new javax.swing.GroupLayout(edit_panel);
        edit_panel.setLayout(edit_panelLayout);
        edit_panelLayout.setHorizontalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_edit_lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_panelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_num_field, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(edit_panelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        edit_panelLayout.setVerticalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_edit_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_num_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        edit_name_field.setDocument(new LimitedDocument(50));
        edit_num_field.setDocument(new LimitedDocument(11));
        edit_email_field.setDocument(new LimitedDocument(50));

        getContentPane().add(edit_panel, "card3");
        edit_panel.setVisible(false);

        add_panel.setBackground(new java.awt.Color(244, 239, 250));
        add_panel.setMaximumSize(new java.awt.Dimension(360, 640));
        add_panel.setMinimumSize(new java.awt.Dimension(360, 640));

        header_add_lbl.setBackground(new java.awt.Color(200, 177, 228));
        header_add_lbl.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        header_add_lbl.setForeground(new java.awt.Color(47, 24, 75));
        header_add_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_add_lbl.setText("ADD CONTACT");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        name_textfield.setBackground(new java.awt.Color(200, 177, 228));
        name_textfield.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textfieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel4.setText("Mobile Number");

        number_textfield.setBackground(new java.awt.Color(200, 177, 228));
        number_textfield.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        number_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_textfieldActionPerformed(evt);
            }
        });
        number_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                number_textfieldKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setText("Email ");

        email_textfield.setBackground(new java.awt.Color(200, 177, 228));
        email_textfield.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        back_btn1.setBackground(new java.awt.Color(200, 177, 228));
        back_btn1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        back_btn1.setForeground(new java.awt.Color(47, 24, 75));
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(200, 177, 228));
        add_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(47, 24, 75));
        add_btn.setText("Add");
        add_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_panelLayout = new javax.swing.GroupLayout(add_panel);
        add_panel.setLayout(add_panelLayout);
        add_panelLayout.setHorizontalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_add_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_panelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(add_panelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        add_panelLayout.setVerticalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_add_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        name_textfield.setDocument(new LimitedDocument(50));
        // Set a PlainDocument with number validation
        number_textfield.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                if (str == null) {
                    return;
                }
                for (char c : str.toCharArray()) {
                    if (!Character.isDigit(c)) {
                        return;
                    }
                }
                super.insertString(offs, str, a);
            }
        });

        number_textfield.setText("09");

        number_textfield.setDocument(new LimitedDocument(11));
        email_textfield.setDocument(new LimitedDocument(100));

        getContentPane().add(add_panel, "card4");
        add_panel.setVisible(false);

        view_panel.setBackground(new java.awt.Color(244, 239, 250));
        view_panel.setMaximumSize(new java.awt.Dimension(360, 640));
        view_panel.setMinimumSize(new java.awt.Dimension(360, 640));
        view_panel.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(200, 177, 228));

        name_lbl_view.setBackground(new java.awt.Color(200, 177, 228));
        name_lbl_view.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        name_lbl_view.setForeground(new java.awt.Color(47, 24, 75));
        name_lbl_view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_lbl_view.setText("CONTACT NAME\n");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(name_lbl_view, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(name_lbl_view, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        view_panel.add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 250);

        okay_btn.setBackground(new java.awt.Color(200, 177, 228));
        okay_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        okay_btn.setText("OKAY");
        okay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_btnActionPerformed(evt);
            }
        });
        view_panel.add(okay_btn);
        okay_btn.setBounds(110, 480, 120, 40);

        number_view.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        number_view.setForeground(new java.awt.Color(47, 24, 75));
        number_view.setText("09123456789");
        view_panel.add(number_view);
        number_view.setBounds(30, 290, 260, 30);

        number_placeholder.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        number_placeholder.setForeground(new java.awt.Color(47, 24, 75));
        number_placeholder.setText("Mobile Number");
        view_panel.add(number_placeholder);
        number_placeholder.setBounds(30, 270, 90, 15);

        email_view.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        email_view.setForeground(new java.awt.Color(47, 24, 75));
        email_view.setText("email@java.com");
        view_panel.add(email_view);
        email_view.setBounds(30, 350, 260, 30);

        email_placeholder.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        email_placeholder.setForeground(new java.awt.Color(47, 24, 75));
        email_placeholder.setText("Email");
        view_panel.add(email_placeholder);
        email_placeholder.setBounds(30, 330, 90, 15);

        getContentPane().add(view_panel, "card5");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String selected_contact;
    
    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here: 
        selected_contact = list.getSelectedValue();
        
        if (selected_contact == null) {
            JOptionPane.showMessageDialog(this, "No contact selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        recent.offer(selected_contact);
        recent_name_lbl.setText(recent.poll());
        
        for(Contact C : contacts){
            if(selected_contact.equals(C.getName())){
                name_lbl_view.setText(C.getName());
                number_view.setText(C.getNumber());
                email_view.setText(C.getEmail());
            } 
        } 
        
        home_panel.setVisible(false);
        view_panel.setVisible(true);
    }//GEN-LAST:event_view_btnActionPerformed

    private void ADD_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_BTNActionPerformed
        // TODO add your handling code here:
        home_panel.setVisible(false);
        add_panel.setVisible(true);
    }//GEN-LAST:event_ADD_BTNActionPerformed

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
        // TODO add your handling code here:
        removeSelectedContact();
        updateRecent();
    }//GEN-LAST:event_del_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        selected_contact = list.getSelectedValue();
        
        if (selected_contact == null) {
            JOptionPane.showMessageDialog(this, "No contact selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        home_panel.setVisible(false);
        add_panel.setVisible(false);
        edit_panel.setVisible(true);
        
        for(Contact C : contacts){
            if(selected_contact.equals(C.getName())){
                edit_name_field.setText(C.getName());
                edit_num_field.setText(C.getNumber());
                edit_email_field.setText(C.getEmail());
            } 
        } 
        
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textfieldActionPerformed

    private void number_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number_textfieldActionPerformed

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        home_panel.setVisible(true);
        add_panel.setVisible(false);
        name_textfield.setText("");
        number_textfield.setText("");
        email_textfield.setText("");
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        addContact();
    }//GEN-LAST:event_add_btnActionPerformed

    private void edit_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_name_fieldActionPerformed

    private void edit_num_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_num_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_num_fieldActionPerformed

    private void edit_email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_email_fieldActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        showHomePanel();
    }//GEN-LAST:event_back_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        name = edit_name_field.getText();
        number = edit_num_field.getText();
        email = edit_email_field.getText();

                
        for(Contact C : contacts){
            if(selected_contact.equals(C.getName())){
                C.editName(name);
                C.editNumber(number);
                C.editEmail(email);
            } 
        } 
        
                        
            if (!validateName(name)) {
                JOptionPane.showMessageDialog(this, "Name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!validateNumber(number)) {
                JOptionPane.showMessageDialog(this, "Number must be 11 digits.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!validateEmail(email)) {
                JOptionPane.showMessageDialog(this, "Enter correct Email format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        JOptionPane.showMessageDialog(this, "Contact Edited Successfully", "Notice", JOptionPane.INFORMATION_MESSAGE);
        
        updateContactList(); 
        showHomePanel();
    }//GEN-LAST:event_save_btnActionPerformed

    private void number_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_number_textfieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_number_textfieldKeyPressed

    private String recent_contact;
    private void recent_name_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recent_name_lblMouseClicked
        // TODO add your handling code here:
        
        recent_contact = recent_name_lbl.getText();
        if (recent_contact.equals("No recently viewed yet.")) { 
            return;
        }
       
        
        home_panel.setVisible(false);
        view_panel.setVisible(true);
        
    }//GEN-LAST:event_recent_name_lblMouseClicked

    private void okay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_btnActionPerformed
        // TODO add your handling code here:
        showHomePanel();
    }//GEN-LAST:event_okay_btnActionPerformed

    private void recent_name_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recent_name_lblMouseEntered
        // TODO add your handling code here:
        if (!(recent_name_lbl.getText().equals("No recently viewed yet."))){
            recent_name_lbl.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18));
        }
         
    }//GEN-LAST:event_recent_name_lblMouseEntered

    private void recent_name_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recent_name_lblMouseExited
        // TODO add your handling code here:
        recent_name_lbl.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); 
    }//GEN-LAST:event_recent_name_lblMouseExited

    /**
     * @param args the command line arguments
     */

    
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new phonebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_BTN;
    private javax.swing.JButton add_btn;
    private javax.swing.JPanel add_panel;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton back_btn1;
    private javax.swing.JLabel contacts_lbl;
    private javax.swing.JButton del_btn;
    private javax.swing.JTextField edit_email_field;
    private javax.swing.JTextField edit_name_field;
    private javax.swing.JTextField edit_num_field;
    private javax.swing.JPanel edit_panel;
    private javax.swing.JLabel email_placeholder;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel email_view;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header_add_lbl;
    private javax.swing.JLabel header_edit_lbl1;
    private javax.swing.JPanel home_panel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JLabel name_lbl_view;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JLabel number_placeholder;
    private javax.swing.JTextField number_textfield;
    private javax.swing.JLabel number_view;
    private javax.swing.JButton okay_btn;
    private javax.swing.JLabel recent_name_lbl;
    private javax.swing.JLabel recently_lbl1;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton view_btn;
    private javax.swing.JPanel view_panel;
    // End of variables declaration//GEN-END:variables



class LimitedDocument extends PlainDocument {
        private int limit;

        public LimitedDocument(int limit) {
            this.limit = limit;
        }

        @Override
        public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
            if (str == null) {
                return;
            }
            if ((getLength() + str.length()) <= limit) {
     
                super.insertString(offs, str, a);
            }
        }
    }
}


